GSM-MSG/GCMS-BackEnd

src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
* 유저 id가 uuid라 binary(16)으로 지정해야됨
* 유저 id binary(16)으로 지정
=> 🔀 :: 35-유저id binary(16)으로 변경

src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt, src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/ClubStatusDto.kt, src/main/kotlin/com/msg/gcms/domain/club/service/CloseClubService.kt, src/main/kotlin/com/msg/gcms/domain/club/service/impl/CloseClubServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt, src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt, src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt, src/test/kotlin/com/msg/gcms/domain/club/controller/CloseClubControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/club/controller/CreateClubControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/club/controller/FindClubListControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/club/service/CloseClubServiceTest.kt
* 동아리 신청 마감 API
* 신청 마감 API 개발
* 테스트 코드
* 시큐리티에 신청 마감 uri 추가
=> 🔀 :: 44-동아리 신청 마감 API

src/main/kotlin/com/msg/gcms/domain/applicant/domain/entity/Applicant.kt, src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt, src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/ClubMember.kt, src/main/kotlin/com/msg/gcms/domain/user/exception/UserIsHeadException.kt, src/main/kotlin/com/msg/gcms/domain/user/presentaion/UserController.kt, src/main/kotlin/com/msg/gcms/domain/user/service/WithdrawUserService.kt, src/main/kotlin/com/msg/gcms/domain/user/service/impl/UpdateProfileImgServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/user/service/impl/WithdrawUserServiceImpl.kt, src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt, src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt, src/test/kotlin/com/msg/gcms/domain/user/controller/FindUserControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/user/controller/SearchUserControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/user/controller/UpdateProfileImgControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/user/controller/WithdrawUserControllerTest.kt, src/test/kotlin/com/msg/gcms/domain/user/service/WithdrawUserServiceTest.kt
* 유저탈퇴 API 구현
* 유저탈퇴 API 구현
* cascade 옵션 추가
* 유저 탈퇴 테스트코드 작성
* 신청자와 멤버 엔티티에 casCade 옵션 추가
=> 🔀 :: 56-유저탈퇴 API

src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt, src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt, src/main/kotlin/com/msg/gcms/global/util/UserUtil.kt
* 프론트의 요청으로 토큰없이 디테일 페이지를 열람할 수 있게 수정했습니다.
* 디테일 페이지를 토큰없이 열람할 수 있도록 작업했습니다.
* userUtils에 email을 가져오는 부분을 함수로 변환
* email에 유무에 따라서 로직이 실행되게 변경
=> 🔀 :: 101 동아리 디테일 페이지 permitAll로 수정

src/main/kotlin/com/msg/gcms/domain/user/service/impl/SearchUserServiceImpl.kt, src/test/kotlin/com/msg/gcms/domain/user/service/SearchUserServiceTest.kt
* 유저 검색시 자신을 검색하면 검색되는 
* 유저 검색시 자신이 안나오도록 필터링
=> 🔀 :: 105 - 유저 검색에 본인이 나오지않도록 수정

src/main/kotlin/com/msg/gcms/domain/club/exception/AlreadyClubHeadException.kt, src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt, src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
* 한 사람이 전공 동아리를 여러개 만들 수 있음
* 자율/전공 동아리 부장이나 구성원이먼 동아리를 생성 못 하도록 수정
=> 🔀 :: 109-자율/전공 동아리 부장혹은 구성원일때 동아리를 생성하지 못하도록 수정

src/main/kotlin/com/msg/gcms/domain/club/utils/SaveClubUtil.kt
* 프론트가 동아리 수정할때 부장을 동아리 멤버 리스트에 보내서 알게된 버그
* 동아리 저장하는 객체에 부장이 동아리 멤버 리스트로 들어가있는지 확인하는 로직 추가
=> 🔀 :: 119-동아리 구성원에 부장이 들어있는지 확인하는 로직 추가

src/main/kotlin/com/msg/gcms/domain/image/utils/impl/ImageValidatorImpl.kt
* 프론트에서 배너이미지와 활동사진을 한번에 보내는 로직처리로 인해 수정이 필요함
* validator조건식에 수를 수정
=> 🔀 ::  118 - 이미지 개수 수정

src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt, src/main/kotlin/com/msg/gcms/domain/admin/service/AcceptClubService.kt, src/main/kotlin/com/msg/gcms/domain/admin/service/impl/AcceptClubServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt, src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
* 어드민이 동아리 생성을 위해 동아리 생성을 허가하는 API
* 로직 구현
=> 🔀 :: 130 - 동아리 수락 API 구현

src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt, src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserServiceImpl.kt
* 유저 정보에 생성되지 않는 동아리 정보가 뜨는 상황
* find조건 수정
* filter로 거르기
=> 🔀 :: 157 - 유저페이지 동아리 정보 로직 수정

src/main/kotlin/com/msg/gcms/domain/auth/domain/entity/RefreshToken.kt
* 다중로그인이 가능하게 변경
* RefreshTokenEntity의 Id를 token으로 변경
=> 🔀 :: 161 - 다중로그인 되게 변경

src/main/kotlin/com/msg/gcms/domain/club/utils/impl/UpdateClubStatusUtil.kt
* 동아리 마감, 재오픈시 동아리가 생성 대기 중으로 돌아감
* status값 추가
=> 🔀 :: 170 - 동아리 마감 여부 수정

src/main/kotlin/com/msg/gcms/domain/user/service/impl/SearchUserServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/user/utils/UserValidator.kt, src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserValidatorImpl.kt, src/test/kotlin/com/msg/gcms/domain/user/service/SearchUserServiceTest.kt
유저 검색시 어드민까지 검색되는 문제를 해결
* validator 생성
* 유저 검증로직 리팩토링
=> 🔀 :: 201 - 유저 검색시 어드민 검색 불가로 만들기

src/main/kotlin/com/msg/gcms/domain/admin/service/impl/FindAllStatisticsServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ClubApplyServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/club/exception/ClubNotOpeningException.kt, src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
동아리가 열리지 않은 상태일때 신청 불가능하게 막음
동아리 isOpened false 인경우 신청 불가능하게 예외 추가
통계 리스트 값 중첩되어지는 현상 으로 초기화 로직 추가
=> 🔀 :: 220 - 동아리가 열리지 않은 상태일때 신청 불가능하게 막음

src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelServiceImpl.kt
* 동아리 제목에 콘론이 들어가고 동아리별로 엑셀을 만들면 에러
* 동아리 제목에 콜론이 들어가면 엑셀로 뽑을때 공백으로 치환하도록 변경
=> 🔀 :: 224 - 동아리 제목에 콜론(:)이 들어갈때 엑셀로 뽑으면 에러

src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/CreateClubRequest.kt, src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/UpdateClubRequest.kt
notionLink 정규식 수정
http:// 또는 https:// 만 허용하던 정규식을 http:// 와 https:// 로 시작하는 url을 허용하는 정규식으로 수정했습니다.
=> 🔀 :: 241 - 정규식 수정

build.gradle.kts, src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt, src/main/kotlin/com/msg/gcms/domain/admin/service/ClubOperationPlanHwpService.kt, src/main/kotlin/com/msg/gcms/domain/admin/service/impl/ClubOperationPlanHwpServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt, src/main/kotlin/com/msg/gcms/domain/club/domain/entity/MonthlyPlan.kt, src/main/kotlin/com/msg/gcms/domain/club/domain/entity/OperationPlan.kt, src/main/kotlin/com/msg/gcms/domain/club/exception/OperationPlanNotFoundException.kt, src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/OperationPlanDto.kt, src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/CreateOperationPlanRequest.kt, src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateOperationPlanServiceImpl.kt, src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt, src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt, src/main/kotlin/com/msg/gcms/global/util/HwpUtil.kt, src/main/kotlin/com/msg/gcms/global/util/impl/HwpUtilImpl.kt, src/main/kotlin/com/msg/gcms/global/util/properties/HwpProperties.kt, src/main/resources/application.yml
동아리 정보와 따로 입력받은 운영계획서용 엔티티의 데이터들을 불러와 한글 파일에 채워서 반환하는 api를 만들었습니다
월별 계획(MonthlyPlan)엔티티의 컬럼이 새로 하나 추가되었어요!!(월별 계획 개요)
코드가 더럽더라도.. 너그러이 이해해주시길..🤢
=> 🔀 Feat/print operation plan

build.gradle.kts
* [build.gradle 파일에 추가](https://github.com/GSM-MSG/GCMS-BackEnd/commit/d91ed310b912a47db69cd0994ecc0ca1f85a5410)된 jar 네이밍 수정하는 부분 제거
* build.gradle에서 jar 네이밍 수정하는 부분 제거
* 죄송합니다...😭
=> 🔀 :: 267 - jar 이름 설정하는 부분 제거

src/main/kotlin/com/msg/gcms/domain/notice/domain/entity/Notice.kt, src/main/kotlin/com/msg/gcms/domain/notice/presentation/NoticeController.kt, src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/dto/NoticeDto.kt, src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/request/CreateNoticeRequestDto.kt, src/main/kotlin/com/msg/gcms/domain/notice/service/CreateNoticeService.kt, src/main/kotlin/com/msg/gcms/domain/notice/service/impl/CreateNoticeServiceImpl.kt, src/main/kotlin/com/msg/gcms/domain/notice/utils/NoticeConverter.kt, src/main/kotlin/com/msg/gcms/domain/notice/utils/impl/NoticeConverterImpl.kt, src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
공지사항 작성 api를 개발했습니다.
title과 content를 받아 공지사항을 개설합니다.
선생님과 동아리 부장이 아니면 예외가 발생합니다.
pr을 머지한 후 앱 푸시알람 기능을 추가하겠습니다.
=> 공지사항 작성 api를 개발했습니다

src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/UserAttendanceStatusListDto.kt, src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt, src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
학생 출석 현황을 조회하는 api Reponse의 id의 이름을 uuid로 변경하였습니다
=> 🔀  :: 학생 출석 현황 조회 response parameter id -> uuid

src/main/kotlin/com/msg/gcms/global/web/WebMvcConfig.kt
=> 🔀  :: gcms from vercel domain cors

src/main/kotlin/com/msg/gcms/domain/notice/exception/NoticeNotFoundException.kt, src/main/kotlin/com/msg/gcms/domain/notice/presentation/NoticeController.kt, src/main/kotlin/com/msg/gcms/domain/notice/service/DeleteNoticeService.kt, src/main/kotlin/com/msg/gcms/domain/notice/service/impl/DeleteNoticeServiceImpl.kt, src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt, src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
공지사항 삭제 api를 구현했습니다
- 공지 사항 삭제 기능 추가
=> 312 delete notice
