GSM-MSG/GCMS-BackEnd

- .github/CODEOWNERS
- .idea/workspace.xml
> 🔀 :: 7- codeowner 추가

- .gitignore
- .idea/misc.xml
- .idea/workspace.xml
- src/main/kotlin/com/msg/gcms/GcmsApplication.kt
- src/main/kotlin/com/msg/gcms/global/redis/RedisConfig.kt
- src/main/kotlin/com/msg/gcms/global/redis/properties/RedisProperties.kt
- src/main/resources/application.yml
> 🔀 :: 5 redis 설정

- src/main/kotlin/com/msg/gcms/domain/applicant/domain/entity/Applicant.kt
- src/main/kotlin/com/msg/gcms/domain/club/domain/entity/ActivityImg.kt
- src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt
- src/main/kotlin/com/msg/gcms/domain/club/enums/ClubType.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/ClubMember.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/enums/MemberScope.kt
- src/main/kotlin/com/msg/gcms/domain/joinStatus/domain/entity/JoinStatus.kt
- src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
ERD에 맞게 엔티티들을 매핑 및 구현하였습니다
첫 실행시 create 후 update로 진행하시면 정상 작동할겁니다
> 🔀 :: 10-ERD에 구현된 엔티티 구현

- src/main/kotlin/com/msg/gcms/domain/auth/domain/entity/RefreshToken.kt
리프레시 토큰을 redis에 저장하기 위해 엔티티를 생성하였습니다
> 🔀 :: 11-RefreshToken 엔티티 생성

- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorResponse.kt
- src/main/kotlin/com/msg/gcms/global/exception/exceptions/BasicException.kt
- src/main/kotlin/com/msg/gcms/global/exception/handler/GlobalExceptionHandler.kt
> 🔀 :: 9-예외처리 설정

- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
> 🔀 :: 19-errorCode 수정

- src/main/kotlin/com/msg/gcms/domain/user/exception/UserNotFindException.kt
- src/main/kotlin/com/msg/gcms/domain/user/exception/UserNotFoundException.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gcms/global/util/UserUtil.kt
> 🔀 :: 22-현재 로그인한 유저 가져오는 객체

- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ActivityImgRepository.kt
- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/ClubDto.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/CreateClubRequest.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/CreateClubService.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/test/kotlin/com/msg/gcms/domain/club/presentation/ClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/presentation/CreateClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImplTest.kt
* 동아리 생성 API개발
* 동아리 생성 기능
* SecurityConfig에 /club이 인증되었을때 통과되도록 설정 추가
> 🔀 :: 24-동아리 생성 API

- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/ClubMember.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/enums/MemberScope.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/enums/MemberScope.kt
ClubMember에 Scope가 불필요해 삭제
ClubMember Entity에 Scope 컬럼 삭제
> 🔀 :: 39-ClubMember에 Scope가 불필요해 삭제

- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ActivityImgRepository.kt
- src/main/kotlin/com/msg/gcms/domain/club/exception/ClubNotFoundException.kt
- src/main/kotlin/com/msg/gcms/domain/club/exception/DirectorNotSameException.kt
- src/main/kotlin/com/msg/gcms/domain/club/exception/HeadNotSameException.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/UpdateClubRequest.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/UpdateClubService.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/SaveClubUtil.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/enums/MemberScope.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/FindClubListControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/CreateClubServiceImplTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/UpdateClubServiceImplTest.kt
* 동아리 수정 API 개발
* 테스트 코드 작성
* 동아리 수정 API 개발
* 업데이트 로직과 생성 로직에서 중복되는 부분을 util로 뺌
> 🔀 :: 38-동아리 수정 API

- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/UserController.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/dto/UserDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/response/UserResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/service/FindUserService.kt
- src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/user/utils/UserConverter.kt
- src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/test/kotlin/com/msg/gcms/domain/user/controller/FindUserControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/user/service/FindUserServiceTest.kt
- src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
- src/test/kotlin/com/msg/gcms/testUtils/UserDataUtil.kt
* 유저 정보 가져오기 API 개발
* 테스트 코드 작성
* 유저 정보 가져오기 API 개발
> 🔀 ::  유저 정보 가져오기 API

- src/main/kotlin/com/msg/gcms/domain/auth/util/AuthConverter.kt
- src/main/kotlin/com/msg/gcms/domain/auth/util/impl/AuthConverterImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt
- src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
- src/test/kotlin/com/msg/gcms/domain/auth/util/AuthConverterTest.kt
- src/test/kotlin/com/msg/gcms/testUtils/AuthDataUtil.kt
- src/test/kotlin/com/msg/gcms/testUtils/TestUtils.kt
> 🔀 :: 23-구현체와 인터페이스 리팩토링

- src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/OpenClubService.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CloseClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/OpenClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/impl/UpdateClubStatusUtil.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/main/kotlin/com/msg/gcms/global/security/auth/AuthDetailsService.kt
- src/main/kotlin/com/msg/gcms/global/util/UserUtil.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/CreateClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/ExitClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/FindClubListControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/OpenClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/ExitClubServiceTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/FindClubListServiceTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/OpenClubServiceTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/UpdateClubServiceImplTest.kt
- src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
동아리 오픈 API
동아리 오픈 API
동아리 오픈 Test code
> 🔀 :: 54 - 동아리 오픈 API

- src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/DeleteClubService.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/DeleteClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/CreateClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/DeleteClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/ExitClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/FindClubListControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/OpenClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/DeleteClubServiceTest.kt
* 동아리 삭제 API
* 동아리 삭제 API개발
* 테스트 코드 작성
* 시큐리티 설정 추가
> 🔀 :: 58 - 동아리 삭제 API

- src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/ClubMemberController.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/dto/ChangeHeadDto.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/dto/DelegateHeadDto.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/request/DelegateHeadRequest.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/service/DelegateHeadService.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/DelegateHeadServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/util/ClubMemberConverter.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/util/UpdateClubHeadUtil.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/util/impl/ClubMemberConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/test/kotlin/com/msg/gcms/domain/clubmember/controller/DelegateHeadControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/clubmember/controller/FindClubMemberListControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/clubmember/service/DelegateHeadServiceTest.kt
* 부장 위임 API
* 부장 위임 API 개발
* 테스트 코드 작성
> 🔀 :: 66 - 부장 위임 API

- src/main/kotlin/com/msg/gcms/domain/auth/domain/repository/RefreshTokenRepository.kt
- src/main/kotlin/com/msg/gcms/domain/auth/exception/ExpiredRefreshTokenException.kt
- src/main/kotlin/com/msg/gcms/domain/auth/presentation/AuthController.kt
- src/main/kotlin/com/msg/gcms/domain/auth/presentation/data/response/NewRefreshTokenResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/auth/service/GetNewRefreshTokenService.kt
- src/main/kotlin/com/msg/gcms/domain/auth/service/impl/GetNewRefreshTokenServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/auth/util/AuthConverter.kt
- src/main/kotlin/com/msg/gcms/domain/auth/util/impl/AuthConverterImpl.kt
- src/test/kotlin/com/msg/gcms/domain/auth/controller/GetNewRefreshTokenControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/auth/controller/SignInControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/auth/service/GetNewRefreshTokenServiceTest.kt
- src/test/kotlin/com/msg/gcms/domain/auth/util/AuthConverterTest.kt
> 🔀 :: 73-AccessToken 재발급 api를 개발하였습니다

- src/main/kotlin/com/msg/gcms/domain/auth/presentation/data/response/SignInResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/auth/service/impl/SignInServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/gauth/GAuthConfig.kt
- src/main/kotlin/com/msg/gcms/global/gauth/properties/GAuthProperties.kt
- src/main/kotlin/com/msg/gcms/global/security/auth/AuthDetailsService.kt
- src/test/kotlin/com/msg/gcms/domain/auth/service/SignInServiceTest.kt
> 🔀 :: 69-이슈터져있던 것들 다 수정

- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
- src/main/kotlin/com/msg/gcms/domain/club/exception/ClubAlreadyExistsException.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
* 동아리 생성할때 같은 이름과 같은 타입의 동아리가 있는지 비교하는 로직이 있어야함
* 비교하는 로직 추가
> 🔀 :: 80 - 동아리가 이미 존재하는지 확인하는 로직추가

- src/main/kotlin/com/msg/gcms/domain/applicant/exception/NotApplicantException.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/presentation/ApplicantController.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/CancelApplicationService.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/CancelApplicationServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/controller/CancelApplicationControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/service/CancelApplicationServiceTest.kt
- src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
* 신청취소 API
* 신청취소 API 개발
* 테스트 코드 작성
> 🔀 :: 82-동아리 신청 취소 API

- src/main/kotlin/com/msg/gcms/domain/auth/domain/repository/RefreshTokenRepository.kt
- src/main/kotlin/com/msg/gcms/domain/auth/presentation/AuthController.kt
- src/main/kotlin/com/msg/gcms/domain/auth/service/LogoutService.kt
- src/main/kotlin/com/msg/gcms/domain/auth/service/impl/LogoutServiceImpl.kt
- src/test/kotlin/com/msg/gcms/domain/auth/controller/GetNewRefreshTokenControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/auth/controller/LogoutControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/auth/controller/SignInControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/auth/service/LogoutServiceTest.kt
- src/test/kotlin/com/msg/gcms/testUtils/AuthDataUtil.kt
로그아웃 기능을 구현
로그아웃 기능 구현
테스트 코드 작성
> 🔀 :: 86-로그아웃 기능 구현

- src/main/kotlin/com/msg/gcms/domain/user/presentaion/UserController.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/dto/UserProfileDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/response/UserProfileResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/service/FindUserProfileService.kt
- src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserProfileServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/user/utils/UserConverter.kt
- src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserConverterImpl.kt
- src/test/kotlin/com/msg/gcms/domain/user/controller/FindUserControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/user/controller/SearchUserControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/user/controller/UpdateProfileImgControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/user/controller/WithdrawUserControllerTest.kt
* 프론트엔드 헤더에 유저 정보를 보내주는 API
* 유저 정보 API 구현
* https://www.notion.so/matsogeum/6344b8672bbe4c9e80a56889ca95fc0f?pvs=4
> 🔀 :: 88 - 유저 미니 프로필 API

- src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
- src/main/resources/application.yml
* uuid로 인한 문제들이 발생했습니다.
* user entity에 uuid 전략 추가
> 🔀 :: 92 - uuid 전략 수정

- src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserConverterImpl.kt
* 동아리 리스트 반환값에 배너이미지 값이 이상했습니다.
* converter에 .name을 .bannerImg로 변경
> 🔀 :: 95 - 동아리 리스트 반환값 수정

- src/main/kotlin/com/msg/gcms/global/web/WebMvcConfig.kt
프론트 테스트 서버와 통신하기 위한 cors 설정 파일 추가
origin url : https://gcms-front-end-v2.vercel.app
allowed methods : POST, PATCH, PUT, DELETE, HEAD
allowed headers : Authorization, Refresh-Token
allowCredentials : true
> 🔀 :: cors 문제 해결

- src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/UpdateClubDto.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/UpdateClubRequest.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/UpdateClubService.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/SaveClubUtil.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
- src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/UpdateClubServiceImplTest.kt
* 동아리 수정시 clubType 안받게 수정
* clubType을 안받아서 clubDto를 사용할수 없어서 SaveClubUtil객체를 수정했습니다
> 🔀 :: 103 동아리 수정시 clubType 안받게 수정

- src/main/kotlin/com/msg/gcms/domain/applicant/presentation/ApplicantController.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/presentation/data/dto/RejectDto.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/presentation/data/request/RejectRequestDto.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/RejectApplicantService.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/AcceptApplicantServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ClubApplyServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/RejectApplicantServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/util/ApplicantConverter.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/util/impl/ApplicantConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/controller/AcceptApplicationControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/controller/CancelApplicationControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/controller/ClubApplyControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/controller/RejectApplicantControllerTest.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/service/AcceptApplicantServiceTest.kt
- src/test/kotlin/com/msg/gcms/domain/applicant/service/RejectApplicantServiceTest.kt
> 🔀 :: 99-동아리 신청 거절 api생성

- src/main/kotlin/com/msg/gcms/GcmsApplication.kt
> 🔀 :: 101-서버의 시간을 서울로 기본세팅하였습니다.

- src/main/kotlin/com/msg/gcms/global/web/WebMvcConfig.kt
로컬에서의 테스트를 위해 `http://localhost:3000` origin 추가
> 🔀 cors origin 추가

- src/main/kotlin/com/msg/gcms/domain/applicant/presentation/ApplicantController.kt
* 안드로이드에서 run을 사용한 api에서 오류가 발생
* run이 사용된 부분을 let으로 변경
> 🔀 :: 115- 반환값에 사용된 함수 변경

- src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
> 🔀 :: 111-동아리 수정하면 복사되는 버그

- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ClubApplyServiceImpl.kt
* 사설동아리에 경우 중복신청이 가능하도록 수정
* 조건문 수정
> 🔀 :: 113 - 사설 동아리 중복신청 허용

- src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt
- src/main/kotlin/com/msg/gcms/domain/club/enums/ClubStatus.kt
* 생성로직 변경
* 클럽 엔티티에 clubStatus추가
* 생성로직 바꿔야 되는줄 알았는데 status만 추가해도 됨
> 🔀 :: 123-동아리 상태 추가

- src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
* config에 role 설정으로 유저가 동아리 생성이 불가능함
* config hasRole 제거
* converter에 값 추가
> 🚑 :: 132 - 동아리 생성 수정

- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gcms/global/security/jwt/JwtTokenProvider.kt
* 토큰재발급시 모든 유저의 토큰이 404로 처리됨
* 토큰 검증식 수정
> 🔀 :: 134 - 토큰 재발급 조건식 수정

- build.gradle.kts
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/CreateClubMemberExcelByClassNumService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/CreateClubMemberExcelService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelByClassNumServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/main/kotlin/com/msg/gcms/global/util/ExcelUtil.kt
- src/main/kotlin/com/msg/gcms/global/util/impl/ExcelUtilImpl.kt
* 동아리 구성원을 엑셀로 출력하는 API
* 각반의 학생이 어떤 동아리에 소속되있는지 엑셀로 만드는 API
* 각 동아리에 소속되있는 유저를 보여주는 API
* 동아리 생성API는 인증만 되면 실행할수있게 수정
* 엑셀 디자인이 좀 구림
> 🔀 :: 126 - 동아리 구성원을 엑셀로 출력하는 API

- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/FindClubListServiceImpl.kt
- src/test/kotlin/com/msg/gcms/domain/club/service/FindClubListServiceTest.kt
- src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
* 동아리 status추가로 로직 수정
* filter추가로 출력값 수정
> 🔀 :: 128-동아리 리스트 로직 수정

- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
* 개발할때 엑셀 permitAll로 하고 hasRole로 안바꿈
> 🔀 :: 141 - hasRole로 변경

- src/main/kotlin/com/msg/gcms/domain/admin/exception/ClubStatusNotPendingException.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/RejectClubService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/RejectClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
* 어드민이 동아리 생성을 거절하는 API 구현
* 비즈니스 로직 생성
* 에러코드 생성
> 🔀 ::144 - 동아리 생성 거절 API

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/PendingClubDto.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/response/PendingClubResponse.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/FindPendingClubListService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/FindPendingClubListServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/admin/util/AdminConverter.kt
- src/main/kotlin/com/msg/gcms/domain/admin/util/impl/AdminConverterImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
* 생성 대기중인 동아리 리스트 출력 API 구현
* 비즈니스 로직 구현
* converter생성
> 🔀 :: 146 - 생성 대기중인 동아리 리스트 API 

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/PendingClubDto.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/response/PendingClubResponse.kt
- src/main/kotlin/com/msg/gcms/domain/admin/util/impl/AdminConverterImpl.kt
> 🔀 :: 신청대기 동아리 리스트에 clubId값 추가

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
> 🔀 :: 동아리 거절 API URL 수정

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/dto/UserDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/dto/UserProfileDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/response/UserProfileResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/response/UserResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
- src/main/resources/application.yml
- src/test/kotlin/com/msg/gcms/testUtils/UserDataUtil.kt
> /user 라우트 부분에 role 응답 추가

- src/main/kotlin/com/msg/gcms/global/security/jwt/JwtTokenProvider.kt
- src/main/kotlin/com/msg/gcms/global/security/jwt/properties/TokenTimeProperties.kt
- src/main/resources/application.yml
* 토큰 시간 조절을 해달라는 클라요청
* 시간을 yml로 변경
* properties로 변경
> 🔀 :: 154 - 토큰 시간 조절

- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
- src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserServiceImpl.kt
* 마이페이지 500
* jpa쿼리와 파라미터 값이 불일치 수정
> 🔀 :: 159 - 마이페이지 오류

- src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
- src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
* 클럽 수정후 상태가 pending으로 돌아가는 오류
* converter에 값 추가
> 🔀 :: 164 - 동아리 수정 로직 변경

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/ClubInfoDto.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/FindAllUserListDto.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/UserDetailInfoDto.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/request/UserDetailInfoRequest.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/response/FindAllUserListResponse.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/response/UserDetailInfoResponse.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/FindAllUserListService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/UserDetailInfoService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/FindAllUserListServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/UserDetailInfoServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/admin/util/AdminConverter.kt
- src/main/kotlin/com/msg/gcms/domain/admin/util/impl/AdminConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
어드민 회원 전체 조회
어드민 부분에서 회원 전체 조회
어드민 부분에서 회원 상세 조회
> 어드민 회원 전체 조회

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/request/UserDetailInfoRequest.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/UserDetailInfoServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
get 에 body 넣어서 Pathvariable로 변경
> get 에 body 넣어서 Pathvariable로 변경

- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
- src/main/kotlin/com/msg/gcms/domain/club/exception/ClubAlreadyPendingException.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
> 동아리 Pending 상태일때 예외처리 추가

- src/main/kotlin/com/msg/gcms/domain/clubMember/util/UpdateClubHeadUtil.kt
> club status 추가 안된 부분 추가

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/FindAllStatisticsDto.kt
- src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/response/FindAllStatisticsResponse.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/FindAllStatisticsService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/FindAllStatisticsServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/admin/util/AdminConverter.kt
- src/main/kotlin/com/msg/gcms/domain/admin/util/impl/AdminConverterImpl.kt
- src/main/kotlin/com/msg/gcms/domain/user/domain/repository/UserRepository.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
> 통계 분석표 데이터 조회 api 

- src/main/kotlin/com/msg/gcms/global/util/impl/MessageSendUtilImpl.kt
* deviceToken이 없으면 메세지를 보내지 않기
> 🔀 :: 186 - deviceToken이 없으면 메세지를 보내지 않기

- src/main/kotlin/com/msg/gcms/domain/user/exception/DeviceTokenNotFoundException.kt
- src/main/kotlin/com/msg/gcms/global/util/impl/MessageSendUtilImpl.kt
* deviceToekn 없으면 예외반환 x
* 바로 return하게 수정
> 🔀 :: 188 - deviceToken이 없으면 return

- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/FindAllStatisticsServiceImpl.kt
동아리 통계 Pending 거르기
Pending 상태인 경우 신청자 수 로 카운트 안하게 변경
> 🔀 :: 190-동아리 통계 Pending 거르기

- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/UserDetailInfoServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
동아리 created 상태에서만 등록 상태 보이게 변경
> 🔀 :: 192-동아리 created 상태에서만 등록 상태 보이게 변경

- src/main/kotlin/com/msg/gcms/global/fcm/FcmConfig.kt
* 어드민이 동아리 생성 수락/거절 시 500 발생
* 에러코드의 해결 방법이라는걸 사용했습니다.
> 🔀 :: 동아리 생성 수락 거절 오류

- src/main/kotlin/com/msg/gcms/global/fcm/FcmConfig.kt
수락 거절 오류로 위장한 fcm오류를 해결해 보겠습니다.
* config 수정
> 🔀 :: 198 - fcm 오류

- src/main/kotlin/com/msg/gcms/domain/admin/exception/NotAceessAdminException.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/FindAllStatisticsServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/exception/SameClubApplicantException.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ApplicantListServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ClubApplyServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/enums/Scope.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CloseClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/OpenClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/DelegateHeadServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/ExitClubMemberServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/user/domain/entity/DeviceToken.kt
- src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
- src/main/kotlin/com/msg/gcms/global/fcm/FcmConfig.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
> 어드민이 필요한 api 에 접근할 수 없는 권한 해결

- src/main/kotlin/com/msg/gcms/global/fcm/FcmConfig.kt
- src/main/resources/application.yml
> 🔀 :: 203-fcm 오류 해결

- src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/DeleteClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/OpenClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/DelegateHeadServiceImpl.kt
* 부장위임을 어드민이 하면 이상하게 되는 버그 수정
* admin인지 검사하는 로직 수정
> 🔀 :: 206 - 부장위임 어드민이 할때 이상한거 해결

- src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ApplicantListServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/FindClubMemberListServiceImpl.kt
> 동아리 상세보기에 Admin Scope 추가

- src/main/kotlin/com/msg/gcms/domain/auth/service/impl/SignInServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt
> 🔀 :: 권한 오류 수정

- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelByClassNumServiceImpl.kt
- src/main/kotlin/com/msg/gcms/global/util/ExcelUtil.kt
- src/main/kotlin/com/msg/gcms/global/util/impl/ExcelUtilImpl.kt
* 엑셀 데이터가 이상함
* 반별로 엑셀 만드는 로직을 갈아엎었음
> 🔀 :: 212 - 엑셀 만드는 로직 수정

- src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/ClubMemberCountExcelService.kt
- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/ClubMemberCountExcelServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/auth/presentation/AuthController.kt
- src/main/kotlin/com/msg/gcms/domain/auth/presentation/data/request/SignInRequestDto.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
> 🔀 :: 214-동아리 인원수 엑셀을 가져오는 API

- src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelServiceImpl.kt
* 동아리별 엑셀에서 학번을 학년, 반, 번호로 분리해야됨
> 🔀 :: 227 - 학번을 학년, 반, 번호로 분리

- src/main/kotlin/com/msg/gcms/domain/user/service/impl/SearchUserServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserValidatorImpl.kt
* 유저 검색이 안되는 오류
* validator에 조건식 수정
> 🔀 :: 231 - 검색안되는 오류 수정

- src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/CreateClubRequest.kt
- src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/UpdateClubRequest.kt
정규식을 추가했습니다.
http 또는 https를 붙어야 허용하게 정규식을 추가했습니다.
> 🔀 :: 233 - 정규식 추가

- src/main/kotlin/com/msg/gcms/global/webhook/util/impl/DiscordUtilImpl.kt
webhook 400 오류가 난다는 제보를 받고 모든 파일을 뒤져보았습니다...
webhook의 400 오류에 대해 찾아보니 json 메세지의 문제인 것 같아 삽질해보니 두 가지 문제가 있더라고요!
1. clubType.name로 설정한 이유가 enum의 description의 내용을 반환하는 줄 알고 (반환타입에 속아서...) 저렇게 설정해놓은건데 그냥 냅다 EDITORIAL. 하고 메세지에 꼽아버리더라고요. when문을 추가해 한 번 변환해주었습니다!
2. ㅎ ㅏ json형식에서 괄호 하나를 빼먹어서... 수정했습니다! <<<<400오류의 주범
clubType.name -> when문을 통해 변환작업 추가
create메세지에서 괄호 하나 빼먹은거 추가
> 🔀 :: 242-webhook 400 오류 해결

- src/main/kotlin/com/msg/gcms/GcmsApplication.kt
- src/main/kotlin/com/msg/gcms/global/config/FilterConfig.kt
- src/main/kotlin/com/msg/gcms/global/logger/LoggingScheduler.kt
- src/main/kotlin/com/msg/gcms/global/logger/filter/RequestLogFilter.kt
- src/main/resources/logback-spring.xml
* 로그를 저장했다가 s3에 보내기
* 전에 작업한 requestLogFilter와 GlobalExceptionHandler, JwtTokenFilter, ExceptionFilter를 logback을 사용해서 로그 파일로 만들고 11:59:59까지 왔던 로그를 s3를 통해 보냄
* body값 파싱이 안되서.... body값은 로깅을 안했습니다..
> 🔀 :: 244 - 로그 정보를 저장했다가 s3에 보내는 로직

- src/main/kotlin/com/msg/gcms/global/logger/LoggingScheduler.kt
- src/main/kotlin/com/msg/gcms/global/webhook/util/DiscordUtil.kt
- src/main/kotlin/com/msg/gcms/global/webhook/util/impl/DiscordUtilImpl.kt
로그내용을 웹훅으로 보낼때 400에러가 뜨던 현상을 해결해보았습니다!
~~요약하자면 문자열이슈였습니다~~
json 변환 과정을 거치지 않은 것, string에서 그대로 \n을 넣은 것 두가지가 문제였네요!
discord util에 단일 메세지 생성 메서드를 추가하고, \n을 \\n으로 바꿔주었습니다!
후에 라이브러리를 만들면 전체적인 리팩토링이 필요할 것 같아요😅
> 로그를 디스코드로 보내기!

- .github/CODEOWNERS
> :adhesive_bandage: CODEOWNERS에 "나" 추가

- docker-compose.yml
docker-compose file에 repository 이름을 붙여줬습니다
docker-compose file에 repository 이름을 붙여줬습니다
이미지 URL과 일치하지않은 오류가 있었습니다 :(
> 🔧 :: AWS repository name 이미지 앞에 추가

- .github/workflows/GCMS-CD.yml
- appspec.yml
- deploy.sh
스크립트를 작성했습니다.
deploy.sh
appspec.yml 
위의 두 파일 작성
> Codedeploy

- src/main/kotlin/com/msg/gcms/domain/health/presentation/HealthCheckController.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
HealthChecker가 서버의 상태를 확인 할 수 있는 healthCheck api를 작성했습니다
> 🔀  :: healthcheck API

- src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Attendance.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Schedule.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/domain/enums/AttendanceStatus.kt
출석 체크 엔티티를 세팅하였습니다
* Club과 1:N 관계인 Schedule 엔티티 작성 (날짜, 시간)을 가짐
* Schedule 1:N 관계인 Attend 엔티티 작성(출석 상태)를 가짐
> 🔀 :: 275 출석 체크 엔티티 세팅

- src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Schedule.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/domain/enums/AttendanceStatus.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/ScheduleDto.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/request/CreateScheduleRequestDto.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/repository/ScheduleRepository.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/service/CreateScheduleService.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/util/ScheduleConverter.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
- src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/ScheduleConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
> 🔀 :: 동아리 출석부 생성 api

- src/main/kotlin/com/msg/gcms/domain/notice/domain/entity/Notice.kt
- src/main/kotlin/com/msg/gcms/domain/notice/domain/repository/NoticeRepository.kt
공지사항 도메인을 세팅했습니다.
- 공지 entity
- 공지 repository
> 공지사항 도메인을 세팅했습니다.

- appspec.yml
- deploy.sh
cd 경로를 appspec.yml에 정의된 경로와 동기화시켰습니다
> 🔀 :: cd 경로 수정

- .github/workflows/GCMS-CD.yml
yml 파일이 append 방식으로 쓰여지던 것을 overwrite 방식으로 변경하였습니다
> 🔀 :: application.yml overwrite

- .github/CODEOWNERS
code owners에 @ta2ye0n 을 추가했습니다.
> code owners 변경

- src/main/kotlin/com/msg/gcms/domain/notice/domain/repository/NoticeRepository.kt
- src/main/kotlin/com/msg/gcms/domain/notice/presentation/NoticeController.kt
- src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/response/NoticeListDto.kt
- src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/response/NoticeListResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/notice/service/NoticeListService.kt
- src/main/kotlin/com/msg/gcms/domain/notice/service/impl/NoticeListServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/notice/utils/NoticeConverter.kt
- src/main/kotlin/com/msg/gcms/domain/notice/utils/impl/NoticeConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
공지사항 리스트 조회를 만들었습니다
공지사항 리스트 조회를 만들어보았습니다
선생님이나 해당 동아리의 부원이 아닐경우 예외가 발생합니다
> 316-notice-list-api

- src/main/kotlin/com/msg/gcms/domain/notice/presentation/NoticeController.kt
- src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/response/FindNoticeDetailResponseDto.kt
- src/main/kotlin/com/msg/gcms/domain/notice/service/FindNoticeDetailService.kt
- src/main/kotlin/com/msg/gcms/domain/notice/service/impl/FindNoticeDetailServiceImpl.kt
- src/main/kotlin/com/msg/gcms/domain/notice/utils/NoticeConverter.kt
- src/main/kotlin/com/msg/gcms/domain/notice/utils/impl/NoticeConverterImpl.kt
- src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
> 🔀 :: 314 공지사항 상세 조회 API
